- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/template/spec/containers/0/image
  value: SERVER_IMAGE # Add your built and pushed server image here.
- op: replace
  path: /spec/template/spec/containers/1/image
  value: BACKEND_IMAGE # Add your built and pushed backend image here.
- op: add
  path: /spec/template/spec/volumes
  value: []
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: backend-code
    hostPath:
      path: /path/to/project/dir
      type: Directory
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: server-code
    hostPath:
      path: /path/to/project/dir/public
      type: Directory
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value: []
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: server-code
    mountPath: /var/app/public
- op: add
  path: /spec/template/spec/containers/1/volumeMounts
  value: []
- op: add
  path: /spec/template/spec/containers/1/volumeMounts/-
  value:
    name: backend-code
    mountPath: /var/app
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Never
- op: add
  path: /spec/template/spec/containers/1/imagePullPolicy
  value: Never