apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: docker-php-example

resources:
- service.yml
- deployment.yml
- ingress.yml
- network-policy.yml
